import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import LoggedOutHeader from "@/components/Headers/LoggedOutHeader";
import ClientWrapper from "@/components/ClientWrapper";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "ProblemsInTheWorld.com",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ClientWrapper>
          <LoggedOutHeader />
          <div className="h-screen pt-16">
            {children}
          </div>
        </ClientWrapper>
      </body>
    </html>
  );
}
