import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import LoggedOutHeader from "@/components/Headers/LoggedOutHeader";
import ClientWrapper from "@/components/ClientWrapper";
import { Provider } from 'react-redux';
import { store } from '@/store';

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "ProblemsInTheWorld.com",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Provider store={store}>
          <ClientWrapper>
            <LoggedOutHeader />
            <div className="h-screen pt-16">
              {children}
            </div>
          </ClientWrapper>
        </Provider>
      </body>
    </html>
  );
}
