import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { AuthProvider } from '@/components/Auth/AuthProvider';
import { MapProvider } from '@/contexts/MapContext';

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "ProblemsInTheWorld.com",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <AuthProvider>
          <MapProvider>
            {children}
          </MapProvider>
        </AuthProvider>
      </body>
    </html>
  );
}
